title: Aru Kudassova
description: "Aru Kudassova â€“ Data Science and Environment"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: kramdown
url: "https://arukudassova.github.io"
baseurl: "/portfolio"
